baseURL: https://анна-богатова.рф # todo: change site url.
title: Анна Богатова # todo: change site name.
defaultContentLanguage: 'en'
theme: eternity
googleAnalytics: '' # todo: set your analytics id.

params:
  image: /images/banner.png
  subtitle: Портфолио
  copyright: Все права защищены.
  author: Анна Богатова
  dontShowSource: true # please, do not do this :)
  portfolio:
    columns:
      desktop:
        nature: 4
        archive: 6
        people: 2
        default: 3
      mobile:
        default: 2
        archive: 3
        people: 1
  socials:
    - icon: 'far fa-envelope fa-lg'
      url: 'mailto:duetlegkiiveterok@yandex.ru'
      landing: true
    - icon: 'fab fa-instagram fa-lg'
      url: 'https://instagram.com/_bogatovaanna_'
    - icon: 'fab fa-telegram fa-lg'
      url: 'https://t.me/bogatova_anya'
    - icon: 'fab fa-vk fa-lg'
      url: 'https://vk.com/bogatova_anya'
  homepage: "/work" # homepage link, mostly same with menu.main[0]
  specialPages:
    - work
    - archive
  bypassWelcomePage: false # redirects "/" to "homepage" when it's true.
  plausible: '' # todo: set your plausible id.
  disableRadius: false 
  moveIt: false  # Moves Title and Meta info down, only visible when scroll.

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: tags

permalinks:
  work: ":filename/"

menu:
  main:
    - name: роспись
      url: /tags/роспись/
      weight: 1
    - name: пастель
      url: /tags/пастель/
      weight: 2
    - name: масло
      url: /tags/масло/
      weight: 3
    - name: разное
      url: /tags/разное/
      weight: 4
    - name: обо мне
      url: /about/
      weight: 5
